@startuml
class Comment {
    + CommentId : int <<get>> <<set>>
    + <<required>> Text : string <<get>> <<set>>
    + <<required>> AuthorId : string <<get>> <<set>>
    + <<required>> CheepId : int <<get>> <<set>>
}
Comment --> "TimeStamp" DateTime
Comment --> "Author" Author
Comment --> "Cheep" Cheep
@enduml
