@startuml
package "Chirp Core" {
!include ./src/Chirp.Core/Classes/Comment.puml
!include ./src/Chirp.Core/Classes/Author.puml
!include ./src/Chirp.Core/Classes/Follow.puml
!include ./src/Chirp.Core/Classes/Cheep.puml
!include ./src/Chirp.Core/obj/Debug/net9.0/Chirp.Core.GlobalUsings.g.puml
!include ./src/Chirp.Core/obj/Debug/net9.0/Chirp.Core.AssemblyInfo.puml
!include ./src/Chirp.Core/obj/Debug/net9.0/.NETCoreApp,Version=v9.0.AssemblyAttributes.puml
!include ./src/Chirp.Core/obj/Debug/net8.0/Chirp.Core.GlobalUsings.g.puml
!include ./src/Chirp.Core/obj/Debug/net8.0/Chirp.Core.AssemblyInfo.puml
!include ./src/Chirp.Core/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
}
@enduml