# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      env:
        GITHUBCLIENTID: ${{ secrets.GITHUBCLIENTID }}
        GITHUBCLIENTSECRET: ${{ secrets.GITHUBCLIENTSECRET }}
        CHIRPDBPATH: ${{ vars.CHIRPDBPATH }}
    - name: Test
      run:
          export GitHub__ClientId="${{ secrets.GITHUBCLIENTID }}"
          export GitHub__ClientSecret="${{ secrets.GITHUBCLIENTSECRET }}"
          dotnet test --no-build --verbosity normal
      env:
        CHIRPDBPATH: ${{ vars.CHIRPDBPATH }}
